services:
  - type: web
    name: united-we-stand-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    rootDir: backend
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000 # This is the default, but good to be explicit

  - type: static
    name: united-we-stand-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    rootDir: frontend
